#!/usr/bin/env bash

set -euox pipefail

if command -v brew &>/dev/null; then
    echo "brew already installed. Exiting..."
    exit 0
fi

/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
