#!/usr/bin/env zsh
set -e

if [[ -z "${STOW_FOLDERS}" ]]; then
  . ~/.config/personal/env
fi

pushd $DOTFILES
for folder in $(echo $STOW_FOLDERS | sed "s/,/ /g")
do
    stow -D $folder
    stow $folder
done
popd
