#!/bin/sh

set -e

MONITOR_STATUS=$(/usr/bin/xrandr | grep " connected" | grep DP1- | awk '{print $2}')
MONITOR=$(/usr/bin/xrandr | grep " connected" | grep DP1- | awk '{print $1}')

if [ "connected" == "$MONITOR_STATUS" ]; then
/usr/bin/xrandr --output eDP1 --off
/usr/bin/xrandr --output "$MONITOR" --auto --scale 1.5x1.5
feh --bg-scale ~/wallpaper.jpg
