# ~/.config/starship.toml
# Kanagawa Dragon theme

format = """
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$python\
$character"""

# Directory module
[directory]
style = "bold #c4b28a" # dragonYellow

# Character module (prompt symbol)
[character]
success_symbol = " [❯](bold #c4746e)"  # red
error_symbol = " [❯](bold #737c73)"  # samuraiRed
vimcmd_symbol = " [❮](bold #8a9a7b)"  # autumnGreen

# Username module
[username]
style_user = "bold #c5c9c5"  # fujiWhite for default foreground
show_always = true
format = "[$user]($style) "

# Git Branch module
[git_branch]
format = " [$branch]($style)"
style = "bold #a6a69c"  # dragon gray

# Git Status module
[git_status]
format = "[[($conflicted$untracked$modified$staged$renamed$deleted)](bold #C34043) ($ahead_behind$stashed)]($style)"
style = "bold #949fb5"  # dragon teal
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

# Git State module
[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bold #a292a3"  # dragon pink

# Command Duration module
[cmd_duration]
format = " [$duration]($style) "
style = "bold #c4b28a"  # dragon yellow

# Python module (virtual environment)
[python]
format = "[$virtualenv]($style) "
style = "bold #8ba4b0"  # crystalBlue

