local o = vim.opt
o.tabstop = 4                                   -- tab width
o.softtabstop = 4                               -- number of spaces to use for a tab
o.shiftwidth = 4                                -- number of spaces to use for (auto)indent
o.expandtab = true                              -- use spaces instead of tabs
o.smartindent = true                            -- autoindent new lines
o.nu = true                                     -- show line numbers
o.rnu = true                                    -- show relative line numbers
o.mouse = 'a'                                   -- enable mouse support
o.showmode = false                              -- don't show mode
o.clipboard = 'unnamedplus'                     -- use system clipboard
o.breakindent = true                            -- autoindent wrapped lines
o.ignorecase = true                             -- ignore case when searching
o.smartcase = true                              --- ignore case if search pattern is all lowercase
o.signcolumn = 'yes'                            -- always show sign column
o.updatetime = 250                              -- time to wait for commands to finish
o.timeoutlen = 300                              -- time to wait for key sequences to finish
o.inccommand = 'split'                          -- show live preview of commands
o.scrolloff = 8                                 -- number of lines to keep visible
o.sidescrolloff = 8                             -- number of columns to keep visible
o.hlsearch = false                              -- don't highlight search results
o.incsearch = true                              -- show search results as you type
o.wrap = false                                  -- don't wrap lines
o.errorbells = false                            -- don't beep on errors
o.swapfile = false                              -- don't use swap files
o.backup = false                                -- don't use backup files
o.undodir = os.getenv 'HOME' .. '/.vim/undodir' -- set undodir
o.undofile = true                               -- enable persistent undo
o.linebreak = true                              -- wrap lines at word boundaries
o.termguicolors = true                          -- enable true colors
