# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Custom prompt format with newline at the end
format = '''
$directory$git_branch$git_status$golang$cmd_duration$time$line_break$character
'''

# Inserts a blank line between shell prompts
add_newline = true

# Replace the '❯' symbol in the prompt with '➜'
[character]
success_symbol = '[➜](bold green) '

[git_status]
disabled = true

# Command duration configuration
[cmd_duration]
min_time = 2000  # Show command duration if it exceeds 2 seconds
format = "took [$duration](bold red)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true


[line_break]
disabled = false

[time]
disabled = false
format = '[$time]($style)'
