#!/bin/sh

PLUGIN_DIR="$CONFIG_DIR/plugins"

##### Defining Colors #####
export KANAGAWA_BG=0xFF181616
export KANAGAWA_FG=0xFFC5C9C5
export KANAGAWA_BLUE=0xFF7FB4CA
export KANAGAWA_RED=0xFFC34043
export KANAGAWA_GREEN=0xFF8A9A7B
export KANAGAWA_YELLOW=0xFFDCA561
export KANAGAWA_ORANGE=0xFFFFA066
export KANAGAWA_PURPLE=0xFF957FB8

##### Bar Appearance #####
sketchybar --bar position=top height=40 blur_radius=30 color="$KANAGAWA_BG" \
           --bar padding_left=2 padding_right=2 \
           --bar icon_size=18 label_size=14 \
           --bar separator_color="$KANAGAWA_FG" separator_height=20 separator_width=2

##### Changing Defaults #####
default=(
  padding_left=5
  padding_right=5
  icon.font="JetBrainsMono Nerd Font:Bold:17.0"
  label.font="JetBrainsMono Nerd Font:Bold:14.0"
  icon.color="$KANAGAWA_YELLOW"
  label.color="$KANAGAWA_RED"
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)

sketchybar --default "${default[@]}" \
           --bar color=$KANAGAWA_BG height=35 \
           --add event aerospace_workspace_change

# left items
sketchybar --add item chevron left \
           --set chevron icon= label.drawing=off \
           --add item aerospace left \
           --set aerospace script="$PLUGIN_DIR/aerospace_workspaces.sh" \
           --subscribe aerospace aerospace_workspace_change \
           --add item front_app left \
           --set front_app label.color="$KANAGAWA_YELLOW" script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

# right items
sketchybar --add item clock right \
           --set clock update_freq=30 icon=  script="$PLUGIN_DIR/clock.sh" click_script='open "itsycal://date/now"'\
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change \
           --add item wifi right \
           --set wifi script="$PLUGIN_DIR/wifi.sh" \
           --subscribe wifi wifi_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke power_source_change \

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
