local Remap = require("greenhill.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<leader>xx", "<cmd>Trouble<cr>", { silent = true, noremap = true })
nnoremap("<leader>xw", "<cmd>Trouble workspace_diagnostics<cr>", { silent = true, noremap = true })
nnoremap("<leader>xd", "<cmd>Trouble document_diagnostics<cr>", { silent = true, noremap = true })
nnoremap("<leader>xl", "<cmd>Trouble loclist<cr>", { silent = true, noremap = true })
nnoremap("<leader>xq", "<cmd>Trouble quickfix<cr>", { silent = true, noremap = true })
nnoremap("gR", "<cmd>Trouble lsp_references<cr>", { silent = true, noremap = true })
nnoremap("<leader>tp", function()
	require("trouble").previous({ skip_groups = true, jump = true })
end)
nnoremap("<leader>tn", function()
	require("trouble").next({ skip_groups = true, jump = true })
end)
