return {
    --     "nvim-telescope/telescope.nvim",
    --     branch = "0.1.x",
    --     dependencies = {
    --         "nvim-lua/popup.nvim",
    --         "nvim-lua/plenary.nvim",
    --         { 'nvim-telescope/telescope-fzf-native.nvim', run = 'make' }
    --     },
    --     config = function()
    --         require("telescope").setup({
    --             pickers = {
    --                 find_files = {
    --                     find_command = {
    --                         "rg",
    --                         "--files",
    --                         "--hidden",
    --                         "--glob",
    --                         "!**/*.git",
    --                     },
    --                 },
    --                 live_grep = {
    --                     file_ignore_patterns = { 'node_modules', '.git', '.venv' },
    --                     find_command = {
    --                         "rg",
    --                         "--no-heading",
    --                         "--with-filename",
    --                         "--line-number",
    --                         "--column",
    --                         "--smart-case",
    --                     },
    --                     additional_args = function(_)
    --                         return { "--hidden" }
    --                     end
    --                 },
    --                 extensions = {
    --                     fzf = {
    --                         fuzzy = true,
    --                         override_generic_sorter = true,
    --                         override_file_sorter = true,
    --                         case_mode = "smart_case",
    --                     },
    --                 },
    --             },
    --         })
    --         local builtin = require("telescope.builtin")
    --
    --         vim.keymap.set('n', '<C-p>', builtin.find_files, {})
    --         vim.keymap.set('n', '<leader>ff', builtin.live_grep, {})
    --     end,
}
